# Generated by Django 6.0.2 on 2026-03-05 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detallepedido_precio_alter_detallepedido_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_mas_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_sin_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vegetariano',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_preferencia', models.CharField(blank=True, choices=[('promocion', 'Productos en promoción'), ('nuevo', 'Productos nuevos'), ('mas_vendido', 'Más vendidos'), ('vegetariano', 'Opciones vegetarianas'), ('sin_gluten', 'Sin gluten')], max_length=20, null=True)),
                ('notificar_promociones', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('productos_favoritos', models.ManyToManyField(blank=True, to='core.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
