# Generated by Django 6.0.2 on 2026-03-05 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_es_mas_vendido_producto_es_nuevo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(blank=True, choices=[('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('entrada', 'Entradas'), ('postre', 'Postres')], max_length=20, null=True)),
                ('tipo_bebida', models.CharField(blank=True, choices=[('caliente', 'Bebidas calientes'), ('fria', 'Bebidas frías'), ('ninguna', 'No me interesan las bebidas')], max_length=20, null=True)),
                ('tipo_proteina', models.CharField(blank=True, choices=[('carne', 'Carne de res'), ('pollo', 'Pollo'), ('pescado', 'Pescado'), ('mariscos', 'Mariscos'), ('vegetariano', 'Vegetariano'), ('ninguna', 'Sin preferencia')], max_length=20, null=True)),
                ('rango_precio', models.CharField(blank=True, choices=[('economico', 'Económico ($0 - $15.000)'), ('medio', 'Medio ($15.000 - $30.000)'), ('alto', 'Alto ($30.000+)')], max_length=20, null=True)),
                ('incluir_promociones', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PreferenciaUsuario',
        ),
    ]
