# Generated by Django 6.0.2 on 2026-03-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_preferenciasusuario_delete_preferenciausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_mas_vendido',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_nuevo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_sin_gluten',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_vegetariano',
        ),
    ]
