# Generated by Django 6.0.2 on 2026-03-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_producto_es_mas_vendido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nivel',
            field=models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('platino', 'Platino')], default='bronce', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_compras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
