# Generated by Django 6.0.2 on 2026-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_nivel_cliente_total_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_mas_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_sin_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vegetariano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
