# Generated by Django 6.0.2 on 2026-03-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_es_mas_vendido_producto_es_nuevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasusuario',
            name='tipo_comida',
            field=models.CharField(blank=True, choices=[('entrada', 'Entradas'), ('postre', 'Postres')], max_length=20, null=True),
        ),
    ]
